name: drone_aid
description: "Drone AID - A drone-based disaster management system."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  # State Management

  provider: ^6.1.5+1
  flutter_riverpod: ^3.0.0

  # Navigation
  go_router: ^16.2.4

  # Location & Maps
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

  # HTTP & Networking
  http: ^1.2.2
  dio: ^5.9.0

  # Local Storage
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilities
  uuid: ^4.5.1
  intl: ^0.20.2
  crypto: ^3.0.3

  # Form Validation
  formz: ^0.8.0

  # Loading & Progress
  flutter_spinkit: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
